name: Build and release
on:
  workflow_dispatch:
  push:
    branches:
      - test-v1

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        BOARD: [radxa-zero, rockpi-4a, rockpi-4b, rockpi-4c, rockpi-e, rockpi-s]
        RELEASE: [buster]
    steps:
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.time.outputs.time }}
          target_commitish: test-v1
          draft: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}
      tag_name: ${{ steps.time.outputs.time }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: |
          ./compile.sh  BOARD=${{ matrix.BOARD }} BRANCH=current RELEASE=${{ matrix.RELEASE }} BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img        
      - name: Upload image
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
          file: ./output/images/*Armbian*img*
          draft: false
      - name: Rollback release
        if: failure()
        uses: author/action-rollback@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
